[[redirects]]
  from = "/"
  to = "/v3/ar/index.html"

[[redirects]]
  from = "/d/"
  to = "/download/"

[[redirects]]
  from = "/a/*"
  to = "/download/"

[[redirects]]
  from = "/s/*"
  to = "/download/*"
